[run]
init_cmds = [["./peach"]]
watch_all = true
watch_dirs = [
	"$WORKDIR/conf",
	"$WORKDIR/models",
	"$WORKDIR/modules",
	"$WORKDIR/routers"
]
watch_exts = [".go", ".ini"]
build_delay = 1500
cmds = [
	["go", "install"],
	["go", "build"],
	["./peach"]
]